name = "New Altenbury Packwiz"
author = "RexcliffeTransit"
version = "25"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b50ac58b8266421258621d0435ae308b756b818109276af7791c50e6d10134ec"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
