name = "Rexcliffe MTR Packwiz"
author = "RX"
version = "3.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a512dcda46e81c771927bbfb521aa9db31dc1ba59e11a965fb37902bfcef52c2"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
