name = "Rexcliffe MTR Packwiz"
author = "RX"
version = "3.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4d6fdc8b2c009428ea62a562622fc219edff31ee1b14d3e970c70ea8c0edcef"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
