name = "New Altenbury Packwiz"
author = "RexcliffeTransit"
version = "25"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f43ff320dbd8faa919a62777f6bb4e58751d67045d14e1098b5378c5d1040a76"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
