name = "Rexcliffe MTR Packwiz"
author = "RX"
version = "3.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70a481ffb669de3b936a05e05d2666358f82cbacaae6f5ed67a38d3b0f75c7fd"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
