name = "New Altenbury Packwiz"
author = "RexcliffeTransit"
version = "25"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "419488c56f7bf2a7d83b2a58733d97be8eb2c7a6ca0795b44af417b9c6f4b718"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
