name = "Rexcliffe MTR Packwiz"
author = "RX"
version = "3.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd899f95de4e279b96d2b882399b634e5a02d18830944ada6dd79e8cbbae96e7"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
