name = "Rexcliffe MTR Packwiz"
author = "RX"
version = "3.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "012c89d7f9a63c83a48a5fba9632f7052fb2f10756a8a3194bc026e672a61f2e"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
