name = "Rexcliffe MTR Packwiz"
author = "RX"
version = "3.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0749e1476506d8174c6a8fcf1a98d2a786ca93a1a654e72582e7a888da545c7d"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
