name = "Rexcliffe MTR Packwiz"
author = "RX"
version = "3.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "219cdbf5dcbb49f922cfe47cd1a1337db2d2b5629f972a0ff00b7d9e3ee05615"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
