name = "New Altenbury Packwiz"
author = "RexcliffeTransit"
version = "25"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "352d88b32e3e71c9959978a065a09fc0b96d8591526b86ec01fa705d320e54c1"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
