name = "Rexcliffe MTR Packwiz"
author = "RX"
version = "3.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9a1634faeaab1cd17bcff98a61558e940450a77c394a224e7b41bee5fa26d59"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
