name = "Rexcliffe MTR Packwiz"
author = "RX"
version = "3.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02d191381beae68aa6615a008c13eef283c574e6565c83a21246805dee775956"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
