name = "Rexcliffe MTR Packwiz"
author = "RX"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9994a682895f15ec1a4d90e5f1a73173744fdb7e50655e9ee7ce4e9920ebc7b6"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
