name = "New Altenbury Packwiz"
author = "RexcliffeTransit"
version = "25"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "450b9fef5023951983a9e7d0a70dfe759ff98b7174bb4161638662ecef18d1b9"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
