name = "Rexcliffe MTR Packwiz"
author = "RX"
version = "3.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e165eccec5d1d60b8afe4df4e9e5db7de3b643c11689f096022897458c31857"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
