name = "New Altenbury Packwiz"
author = "RexcliffeTransit"
version = "25"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f74744ca83c286fc7fcf0ce491e3961a466e0c5c6f524ad112ae00214bc9414b"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
