name = "New Altenbury Packwiz"
author = "RexcliffeTransit"
version = "25"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7af96b7eda920f8dce3e1e0911fbf4db9e813c3dd898b877441e4d7df9fbcdf8"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
