name = "Rexcliffe MTR Packwiz"
author = "RX"
version = "3.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0bcf43aaabfee60eebba693ed3ae8e296088e38835e9a915b94bebb4659f6215"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
