name = "New Altenbury Packwiz"
author = "RexcliffeTransit"
version = "25"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e674cbbb085f9aff3e90ee479d0c43b3b1e65bc7a5f5ed711e7f8e34b997e60e"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
