name = "New Altenbury Packwiz"
author = "RexcliffeTransit"
version = "25"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0cbfd0ad7a0bc7f948c7ed318c71fe0ef3ad78e0435c55b89e42121b0def2180"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
