name = "Rexcliffe MTR Packwiz"
author = "RX"
version = "3.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fddd7034915c031ab5b70da3fdff38e1d1bf8407be5522a054b83da50bae8805"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
