name = "New Altenbury Packwiz"
author = "RexcliffeTransit"
version = "25"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb7f5ad4c057c7d60b31d50aeed31bbd22c5631489a3eeb0a7d1160b20f1a63d"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
