name = "New Altenbury Packwiz"
author = "RexcliffeTransit"
version = "25"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2b22bac5bcc9d3fa1f68f76486faf677d8a7986f75a93052b703cc0ea4fd887"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
